// Copyright (c) 2024 Advanced Micro Devices, Inc.

#ifndef GUARD_ONNX_CUSTOM_OPS_CUSTOM_OPS_OPTIONS
#define GUARD_ONNX_CUSTOM_OPS_CUSTOM_OPS_OPTIONS

#cmakedefine ONNX_UTILS_EP "@ONNX_UTILS_EP@"
static const char kOnnxUtilsEp[] = ONNX_UTILS_EP;
#cmakedefine ONNX_UTILS_ENABLE_PROJECT_DD
#cmakedefine ONNX_UTILS_ENABLE_PROJECT_HYBRID_LLM
#cmakedefine ONNX_UTILS_ENABLE_PROJECT_HYBRID_LLM_CPU
#cmakedefine ONNX_UTILS_ENABLE_PROJECT_HYBRID_LLM_GPU
#cmakedefine ONNX_UTILS_ENABLE_PROJECT_HYBRID_LLM_NPU
#cmakedefine ONNX_UTILS_ENABLE_PROJECT_SHARED_MEMORY
#cmakedefine ONNX_UTILS_ENABLE_CORELIB
#cmakedefine ONNX_UTILS_USE_RYZENAI_EP
#cmakedefine ONNX_UTILS_RYZENAI_EP_NAME "@ONNX_UTILS_RYZENAI_EP_NAME@"

#endif  // GUARD_ONNX_CUSTOM_OPS_CUSTOM_OPS_OPTIONS
