# Copyright (C) 2024 - 2025 Advanced Micro Devices, Inc. All rights reserved.

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ryzenai_onnx_utils"
version = "0.10.0.dev0"
description = "onnx utils"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "colorlog",
  "numpy",
  "onnx",
  "onnx_tool",
  "ml_dtypes",
  "pyyaml",
  "rich",
  "sympy",
]

[project.optional-dependencies]
dev = [
  "mypy",
  "pre-commit",
  "pytest",
  "types-pyyaml"
]

docs = [
  "sphinx_copybutton",
  "sphinx-argparse",
  "sphinx-favicon",
  "sphinx-issues",
  "sphinx-tabs",
  "sphinx-tippy",
  "sphinx",
  "sphinxcontrib-jquery",
  "sphinxemoji",
  "sphinx_rtd_theme",
  "sphinx-toolbox",
]

[project.scripts]
onnx_utils = "ryzenai_onnx_utils.partitioner:main"

# This will compile the proto files for Python whenever the wheel is built. By
# having this here, proto files will always be added into the wheel, instead of
# respecting the .gitignore rules, so comment it out if you want to exclude them
# using .gitignore
[tool.hatch.build.hooks.protobuf]
dependencies = ["hatch-protobuf", "protobuf==6.31.1"]
generate_grpc = false
proto_paths = ["src/onnx_custom_ops/"]
output_path = "src/ryzenai_onnx_utils/proto"

[tool.ruff]
line-length = 120
target-version = "py310"

[tool.ruff.lint]
select = [
  # pycodestyle
  "E",
  "W",
  # Pyflakes
  "F",
  # pyupgrade
  "UP",
  # flake8-bugbear
  "B",
  # flake8-simplify
  "SIM",
  # isort
  "I",
  # comprehension and complexity
  "C"
]
ignore = [
  # complex-structure - ignored with too many violations for now
  "C901",
  # line-too-long - fixed by linters
  "E501",
]

[tool.ruff.lint.isort]
known-first-party = ["ryzenai_onnx_utils"]

[tool.ruff.lint.extend-per-file-ignores]
"__init__.py" = ["F401"]

[tool.mypy]
mypy_path = "./src"
strict = true
disable_error_code = ["method-assign", "unused-ignore"]
# these third-party modules have untyped calls
untyped_calls_exclude = ["safetensors"]

# these third-party modules are not type annotated
[[tool.mypy.overrides]]
module = [
  "onnx_tool.*",
  "onnxruntime.*",
  "ryzenai_dynamic_dispatch.*",
  "sympy.*",
]
ignore_missing_imports = true

# auto-generated files should not be type checked
[[tool.mypy.overrides]]
module = "ryzenai_onnx_utils.proto.*"
ignore_errors = true

# TODO: these files need to be type checked
[[tool.mypy.overrides]]
module = [
  "ryzenai_onnx_utils.passes.sd15.*",
  "ryzenai_onnx_utils.passes.sd3_5.*",
  "ryzenai_onnx_utils.passes.sd3.*",
]
ignore_errors = true
